### ISSUE TITLE
  New device support.

### ISSUE THREAD

**Issue by adruha** [userx14/omblepy#16]
Can you make support for another Omron RS2 Intelli IT (HEM-161T) device? I tried to connect but without success.

**Comment by userx14** [comment]
Hi @adruha ,

can you go a bit into detail on what "connect but without success" means 
(e.g. does the error happen while pairing or later while transmitting the data, is there some error in debug output when you use the debugging flag,... )?
The device seems to simmilar to the hem-6232t, have you tested with this driver yet or is the pairing not working?
Probably it needs a little modification, since hem-6232t has two users while hem-6161t only has a single user.

Best,
Benjamin

**Comment by adruha** [comment]
2023-07-29 17:50:44,081 - omblepy - INFO - Attempt connecting to 00:5F:BF:29:FE:36.
2023-07-29 17:50:47,094 - omblepy - INFO - unpair and disconnect
Traceback (most recent call last):
  File "omblepy.py", line 373, in main
    await bluetoothTxRxObj.writeNewUnlockKey()
  File "omblepy.py", line 222, in writeNewUnlockKey
    raise ValueError(f"Could not enter key programming mode. Has the device been started in pairing mode? Got response: {deviceResponse}")
ValueError: Could not enter key programming mode. Has the device been started in pairing mode? Got response: bytearray(b'\x82\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "omblepy.py", line 389, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "omblepy.py", line 387, in main
    await bleClient.disconnect()
  File "/usr/local/lib/python3.7/dist-packages/bleak/__init__.py", line 540, in disconnect
    return await self._backend.disconnect()
  File "/usr/local/lib/python3.7/dist-packages/bleak/backends/bluezdbus/client.py", line 413, in disconnect
    assert self._bus is None
AssertionError

**Comment by adruha** [comment]
above is what I get.

**Comment by userx14** [comment]
So the issue is in the pairing phase. 
Does the omron device shows the blinking -P- on the screen while you try to execute the -p command?
Which bluetooth chipset / dongle are you using?
I see that you are using linux, is it possible for you to test with Windows on the same machine or on another machine, 
to narrow the problem down?
On linux i had quiet some difficulty getting bluetooth le pairing to work, only some very specific versions of bluez worked, and using a machine with two bluetooth adapters was nearly impossible.

**Comment by adruha** [comment]
yes device shows the blinking P!

hciconfig -a
hci0:   Type: Primary  Bus: USB
        BD Address: 00:1A:7D:DA:71:13  ACL MTU: 310:10  SCO MTU: 64:8
        UP RUNNING
        RX bytes:375322 acl:0 sco:0 events:14160 errors:0
        TX bytes:4135 acl:0 sco:0 commands:357 errors:0
        Features: 0xff 0xff 0x8f 0xfe 0xdb 0xff 0x5b 0x87
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy: RSWITCH HOLD SNIFF PARK
        Link mode: SLAVE ACCEPT
        Name: 'raspiweather'
        Class: 0x000000
        Service Classes: Unspecified
        Device Class: Miscellaneous,
        HCI Version: 4.0 (0x6)  Revision: 0x22bb
        LMP Version: 4.0 (0x6)  Subversion: 0x22bb
        Manufacturer: Cambridge Silicon Radio (10)

**Comment by adruha** [comment]
unfortunately there is no way to check in windows

**Comment by userx14** [comment]
Do you get a pairing confirmation dialog on you linux machine?

If you do not have any windows pc available, but you have an android phone you could try to use the [NRF Connect App](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=de&gl=US&pli=1) and check if the pairing procedure works with android. 
1. Download, extract and copy [this xml file](https://github.com/userx14/omblepy/files/12209568/OmronTest.zip) to you android phone
2. Start omron device in pairing mode
3. In the NRF Connect App, go to Devices -> Scanner, and connect with your omron device
4. Accept the pairing dialog (there might be two which need to be accepted)
5. "Open tab" in the Scanner menu on the omron device /navigate to the rightmost tab which should have the name of your bt device
6. Open the macro menu, (red button with three horizontal lines and play icon, bottom right corner)
7. Hit the blue "download icon" button to import the xml file from step 1
8. Open the macro and use step by step execution (right arrow, with point below) and check the display of the omron device, it should switch from "p" to "o" and then turn off

The general pairing routine is as far as I know shared across all omron devices, so this is most likely one of the following things:
- bug in bluez bluetooth stack related to bluetooth pairing, not sure if it is spefic to bluetooth le
- bluetooth dongle is missing support for some newer bluetooth features, some of the omron devices require bt 4.2 features
