### ISSUE TITLE
Please add 2 in 1 Veroval® ECG and blood pressure monitor device support

### ISSUE THREAD

**Issue by KAMI911** [userx14/omblepy#17]
Hi!
Could you add plugin for 2 in 1 Veroval® ECG and blood pressure monitor device support? I started sharing information here:
 [UBPM issue](https://codeberg.org/LazyT/ubpm/issues/48).
But I have idea, how to really connect for this device. My maing gola to create plugin for UBPM. Could you help me? Also I can provide information if I not provided enough information in [UBPM issue](https://codeberg.org/LazyT/ubpm/issues/48).

Thank you in advance!

**Comment by userx14** [comment]
Hi @KAMI911

Unfortunatelly I do not have that much free time currently, so I have to limit myself to some blanket observations / tips.

The data readout works with a windows application written in dotNet?
One can use [ILSpy](https://github.com/icsharpcode/ILSpy) to inspect dotnet applications and dlls. 

Some older devices of them seem to use serial communication, maybe the did not reinvent the wheel when switching to bluetooth, but that's just a guess:
https://github.com/topics/veroval

A comment regarding the wireshark log:
I would ignore the Wireshark "Analysis" of the "Bluetooth Attribute Protocol" part,  just focus on the raw bytes. From comparing the packets, I would conclude that the packes have an header of some sort:
```
very first response:
1b1500000401360411707900

first block packet:
1b1500010402000142504da6751127000142504d2d3033
1b1500020402011170790011010100050e80000a0a0055
1b15000304020250a5af0080ff7fff0022000000010000
1b15000404020364370002000000000000ffffffff0038  
1b150005040204880043000300002700ffffffffffffff

second block packet:
1b1500060402000242504da6751127000142504d2d3033
1b1500070402011170790017020612222180000a0a0055
1b15000804020250a5af0080ff7fff0022000000010000
1b15000904020364370002000000010000ffffffff0030
1b15000a040204910047000400002700ffffffffffffff

very last packet:
1b15002304
```

some observations (python array notation) based on a quick glance:
packetBytes[2:4] looks like a running index for all packets
packetBytes[4:6] could be a packet type identifier (only changes for very first packet)
packetBytes[6:7] seems to be a running index per block
packetBytes[7: ] seems to be the data you are interested in, also there is very little difference between the different blocks for the first subtransmission.

It is very helpfull to have the correct readings (even better directly converted as hex characters) next to these bytes and just check if you can identify parts.

If you have any questions, please let me know.

Best,
Benjamin
