### ISSUE TITLE
Read data is realtime

### ISSUE THREAD

**Issue by jainkuniya** [userx14/omblepy#18]
This works perfectly for HEM-7361T, thanks a lot building it.

Now moving forward, we were able to export all data in CSV, we wanted to know is there any way we can get real time notification whenever a new Blood pressure reading is taken on the device.

Thanks!

**Comment by userx14** [comment]
Hi @jainkuniya ,

> thanks a lot building it.

Glad you like it 😃.

> Now moving forward, we were able to export all data in CSV, we wanted to know is there any way we can get real time notification whenever a new Blood pressure reading is taken on the device.

Are you refering to the "auto-sync" feature, where after the last measurement the app is able to read in the most recent measurment? 
I've just investigated the behavior of the device and it's actually quiet clever: 
After finishing the measurement and displaying the result, the device enables its bluetooth visibility for a short timespan.
When you start omblepy while the device is just finished measuring, you can pull the measurments, as if you would have started the bluetooth transfer mode with the dedicated key when the device was powered off.

I would assume that the omron app just remembers the bluetooth mac-address and is constantly scanning for this device, or maybe there is a notification for already paired devices on android. As soon as it sees that the device is visible again, it starts the data transfer, while only reading in the new records and resets the eeprom counter for the unread measurments.

You could emulate this by building a script that constantly searches for the mac address of your HEM-7361T, and if it is vislbe start omblepy with the -n flag.

Hope that answers your questions.

Have a nice weekend,
Benjamin
