### ISSUE TITLE
I confirm the functioning of the Omron M4 Inteli IT :)

### ISSUE THREAD

**Issue by RobertWojtowicz** [userx14/omblepy#30]
@userx14 

Tested M4 Intelli IT works as M400 (HEM-7155T), can be added to matrix :)

BR,
Robert

**Comment by userx14** [comment]
Hi Robert,

it's already there, but I really should order the rows so it's easier to find.
But it would be interesting for me to know with which platform you tested?

Regards
Benjamin

**Comment by RobertWojtowicz** [comment]
Hi @userx14

In the matrix there is no information about the M4, I already take out, today successful tests were made on: 
Hardware: Raspberry PI 5 8GB, internal BT;
OS: Raspberry Pi OS (based on Debian 12, 64bit).

BR,
Robert

**Comment by RobertWojtowicz** [comment]
@,

I confirm correct operation also with M7.

BR,
Robert

**Comment by RobertWojtowicz** [comment]
@userx14 

I confirm correct operation also with M7 on this setup

BR,
Robert

**Comment by userx14** [comment]
Thanks for testing,
I have added Raspberry Pi 4B and 5 with "Raspberry Pi OS (64-bit)" to the list of supported os / hardware.

**Comment by RobertWojtowicz** [comment]
> Thanks for testing,
> I have added Raspberry Pi 4B and 5 with "Raspberry Pi OS (64-bit)" to the list of supported os / hardware.

@userx14 ,

You're welcome, I'm glad to be a part of this project :)

BR,
Robert

**Comment by RobertWojtowicz** [comment]
@userx14

To Omron device support matrix, in case of M7 Intelli IT, in section of testers add RobertWojtowicz.

BR,
Robert
